### ISSUE TITLE
bug: seeking audio is broken

### ISSUE THREAD

**Issue by longrunningprocess** [sillsdev/web-languageforge#1644]
**Describe the bug**

When dealing with an audio recording on an element, if you move the slider, neither the playback nor the current time position update. 

**To Reproduce**

1. Go to a project with audio available in entries, e.g., test-chris-02 in staging.
2. move the slider and notice the current time doesn't change.
3. Click play and noticed that the audio starts from the beginning
4. (there is also a console error (`this.$element.find(...).get is not a function`)

**Expected behavior**

Of course, the playback and current time position should be updated.

**Additional context**

This was most likely introduced in #1611 when jquery was removed.

ref:  https://github.com/sillsdev/web-languageforge/blob/develop/src/angular-app/bellows/shared/sound-player.component.ts#L19

**Comment by longrunningprocess** [comment]
> Oof. I did go looking for other jQuery dependant selectors. I can't remember if I checked usages of `find()`.

no worries, we'll get all this cleaned up.

**Comment by megahirt** [comment]
Is it possible to manipulate the slider and evaluate the result in a
playwright test?
